export const brand = {
  name: "Rezist!",
  shortName: "Rezist",
  legalName: "Rezist - A Dessert Lounge",
  handle: "rezist.pk",
  tagline: "IF YOU CAN",
  slogan: "An Ir-Rezistable Delight",
  bio: "An Ir-Rezistable Dessert Lounge in Gujrat, Kharian, Jhelum, Sargodha, Daska, Mirpur & Lala Musa.",
  category: "Dessert Lounge",
  phone: "+92 331 4213137",
  phoneHref: "tel:+923314213137",
  email: "rezist.pk@gmail.com",
  emailHref: "mailto:rezist.pk@gmail.com",
  instagram: "rezist.pk",
  instagramUrl: "https://www.instagram.com/rezist.pk/",
  facebookUrl: "https://www.facebook.com/people/Rezistpk/100091494503304/",
  mapsUrl: "https://maps.app.goo.gl/vJctzif5G83gHBxu7",
  websiteHint: "rezist.pk",
  hqAddress: "Rehman Shaheed Road, Gujrat, 50700",
  hqCity: "Gujrat",
  cities: ["Gujrat", "Kharian", "Jhelum", "Sargodha", "Daska", "Mirpur", "Lala Musa"] as const,
  followersLabel: "40K+ on Instagram",
  logo: "/brand/logo.jpg",
  heroImage: "/brand/hero-cake.jpg",
  gallery: [
    "/brand/ig-1.jpg",
    "/brand/ig-2.jpg",
    "/brand/ig-3.jpg",
    "/brand/ig-4.jpg",
    "/brand/gallery-1.jpg",
    "/brand/gallery-2.jpg",
    "/brand/gallery-3.jpg",
  ],
  websiteModel: "layers.pk",
  freeDeliveryMin: 1000,
  colors: {
    pearlWhite: "#F8F6F0",
    pearlSoft: "#FFFEF9",
    pearlWarm: "#F3EFE6",
    brown: "#5C4033",
    brownSoft: "#7A5A48",
    brownMuted: "#9A7B6A",
    shineGold: "#C49A1A",
    goldHighlight: "#E8C547",
    goldDeep: "#7A5F10",
    metallicBlack: "#0B0B0B",
  },
} as const;
