export const brand = {
  name: "Rezist!",
  shortName: "Rezist",
  tagline: "IF YOU CAN",
  slogan: "An Ir-Rezistable Delight",
  category: "Dessert Shop",
  phone: "+92 331 4213137",
  phoneHref: "tel:+923314213137",
  email: "rezist.pk@gmail.com",
  emailHref: "mailto:rezist.pk@gmail.com",
  instagram: "rezist.pk",
  instagramUrl: "https://www.instagram.com/rezist.pk/",
  facebookUrl: "https://www.facebook.com/people/Rezistpk/100091494503304/",
  websiteHint: "rezist.pk",
  hqAddress: "Rehman Shaheed Road, Gujrat, 50700",
  hqCity: "Gujrat",
  logo: "/brand/logo.jpg",
  heroImage: "/brand/hero-cake.jpg",
  gallery: ["/brand/gallery-1.jpg", "/brand/gallery-2.jpg", "/brand/gallery-3.jpg"],
} as const;
