services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rezist
      POSTGRES_PASSWORD: rezist
      POSTGRES_DB: rezist
    ports:
      - "5432:5432"
    volumes:
      - rezist_pg:/var/lib/postgresql/data

volumes:
  rezist_pg:
